name: Build and Deploy App

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository code
              uses: actions/checkout@v6

            - name: Install dependencies
              run: dotnet restore  

            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "10.x"

            - name: Build
              run: dotnet build --no-restore
